export const DASHBOARD = '/'
export const SIGN_UP = '/register'
export const PROFILE = '/p/:username'
export const NOT_FOUND = '/not-found '
export const LOGIN = '/login'
export const LOGOUT = '/logout'